# Define a zona de limite de requisições por IP (WAF/Rate Limiting Básico)
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=30r/s;

server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Cabeçalhos de Segurança HTTP (Boas práticas DevSecOps / Cloud Security)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy Reverso para a API Spring Boot (Docker Network Internal)
    location /api/ {
        # Aplica o Rate Limiting da zona criada (aceita picos de 50 requests)
        limit_req zone=api_limit burst=50 nodelay;
        
        proxy_pass http://sga-backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
